In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

Original array: [1 2 3 4 5]


In [2]:
print("Array after adding 2 to each element:", arr+2)
print("Array after multiplying each element by 3:", arr*3)
print("Array after dividing each element by 2:", arr/2)

Array after adding 2 to each element: [3 4 5 6 7]
Array after multiplying each element by 3: [ 3  6  9 12 15]
Array after dividing each element by 2: [0.5 1.  1.5 2.  2.5]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = np.flip(arr)
print("Reversed array:", reversed_arr)

Reversed array: [5 4 6 3 2 1]


In [4]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    most_frequent = values[np.argmax(counts)]
    
    indices = np.where(arr == most_frequent)[0]
    return most_frequent, indices

most_frequent_x, indices_x = most_frequent(x)
print("For array x: Most frequent value is",most_frequent_x,"at indices",indices_x)

most_frequent_y, indices_y = most_frequent(y)
print("For array y: Most frequent value is",most_frequent_y, "at indices",indices_y)


For array x: Most frequent value is 1 at indices [0 5 7 8 9]
For array y: Most frequent value is 1 at indices [0 1 2]


In [5]:
import numpy as np
your_name = np.linspace(10, 100, 25)

print("Array:", your_name)

print("Dimensions:", your_name.ndim)

print("Shape:", your_name.shape)

print("Total elements:", your_name.size)

print("Data type of each element:", your_name.dtype)

print("Total bytes consumed by the array:", your_name.nbytes)

transposed_array = your_name.reshape((25, 1))
print("Transposed array using reshape():\n", transposed_array)

transposed_array_t = your_name.T
print("Transposed array using T attribute:\n", transposed_array_t)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type of each element: float64
Total bytes consumed by the array: 200
Transposed array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [8]:
import numpy as np
ucs420_name = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

mean_value = np.mean(ucs420_name)
median_value = np.median(ucs420_name)
max_value = np.max(ucs420_name)
min_value = np.min(ucs420_name)
unique_elements = np.unique(ucs420_name)

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique elements:", unique_elements)

reshaped_ucs420_name = ucs420_name.reshape(3, 4)
print("\nReshaped array to 3 rows and 4 columns:\n", reshaped_ucs420_name)

ucs420_name.resize((2, 6)) 
print("\nResized array to 2 rows and 6 columns (in-place):\n", ucs420_name)



Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array to 3 rows and 4 columns:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Resized array to 2 rows and 6 columns (in-place):
 [[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
