In [5]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]


In [6]:
print("Sum of all elements:",  np.sum(gfg))
print("Sum of all elements row-wise:",np.sum(gfg, axis=1))
print("Sum of all elements column-wise:",np.sum(gfg, axis=0))

Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


In [7]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])

print("Sorted array:",np.sort(array))
print("Indices of sorted array:", np.argsort(array))
print("4 smallest elements:",np.sort(array)[:4])
print("5 largest elements:",np.sort(array)[-5:])


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [8]:
import numpy as np
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

print("Integer elements only:",array[array.astype(int) == array])
print("Float elements only:", array[array.astype(int) != array])


Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [10]:
import numpy as np

initials = "S J"
ascii_sum = sum(ord(char) for char in initials if char != ' ')  # Ignore spaces
X = ascii_sum  

sales = np.array([X, X + 50, X + 100, X + 150, X + 200])

print("Sum of ASCII values (X):", X)
print("sales dataset:", sales)


Sum of ASCII values (X): 157
sales dataset: [157 207 257 307 357]


In [13]:

tax_rate = ((X % 5) + 5) / 100
sales = np.array([X, X + 50, X + 100, X + 150, X + 200])
sales_with_tax = sales * (1 + tax_rate)

print("Tax rate:", tax_rate)
print("Sales with tax applied:", sales_with_tax)


Tax rate: 0.07
Sales with tax applied: [167.99 221.49 274.99 328.49 381.99]


In [14]:
discounted_sales = np.where(sales_with_tax < (X + 100), sales_with_tax * 0.95, sales_with_tax * 0.90)
print("Discounted sales:", discounted_sales)


Discounted sales: [159.5905 210.4155 247.491  295.641  343.791 ]


In [15]:
weekly_sales = np.tile(discounted_sales, (3, 1))  

# Increase sales by 2% per week using broadcasting
weeks = np.arange(3)  
sales_with_increase = weekly_sales * (1 + 0.02 * weeks[:, np.newaxis])  

print("Sales matrix for 3 weeks (before increase):")
print(weekly_sales)
print("Sales matrix for 3 weeks (after 2% increase per week):")
print(sales_with_increase)


Sales matrix for 3 weeks (before increase):
[[159.5905 210.4155 247.491  295.641  343.791 ]
 [159.5905 210.4155 247.491  295.641  343.791 ]
 [159.5905 210.4155 247.491  295.641  343.791 ]]
Sales matrix for 3 weeks (after 2% increase per week):
[[159.5905  210.4155  247.491   295.641   343.791  ]
 [162.78231 214.62381 252.44082 301.55382 350.66682]
 [165.97412 218.83212 257.39064 307.46664 357.54264]]
